version: 1

formatters:
    simple:
        format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

root:
    level: INFO
    handlers: [console]

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
